language: c

install:
 - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install
        git
        make
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        valac

script:
 - make prefix=/usr
 - make install prefix=/usr
